/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GamePanel.java
 *
 * Created on Aug 5, 2010, 9:08:14 PM
 */

package com.pokware.pokertester;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import com.google.protobuf.Message;
import com.pokware.client.ServerEventListener;
import com.pokware.client.netty.PokerClient;
import com.pokware.client.netty.RequestFailedException;
import com.pokware.protobuf.Events.BetEvent;
import com.pokware.protobuf.Events.DealCardsEvent;
import com.pokware.protobuf.Events.FlopEvent;
import com.pokware.protobuf.Events.HandStartEvent;
import com.pokware.protobuf.Events.SeatStatusEvent;
import com.pokware.protobuf.Events.TableStatusEvent;
import com.pokware.protobuf.Events.TimeOutEvent;
import com.pokware.protobuf.Events.TurnEvent;
import com.pokware.protobuf.Events.WinEvent;
import com.pokware.protobuf.ProtobufTools;

/**
 * 
 * @author fabien
 */
public class GamePanel extends javax.swing.JPanel implements ServerEventListener {

	private static final long serialVersionUID = 1L;
	private PokerClient pokerClient;
	private Long gameId;
	private SeatPanel userPanel = null;

	/** Creates new form GamePanel */
	public GamePanel() {
		initComponents();
	}

	public GamePanel(PokerClient pokerClient, Long gameId) {
		initComponents();

		this.pokerClient = pokerClient;
		this.gameId = gameId;
		pokerClient.addServerEventListener(gameId, this);

		int i = 0;
		for (final SeatPanel seatPanel : seatPanelList) {
			final int index = i;
			seatPanel.getSitButton().addActionListener(new ActionListener() {
				@Override
				public void actionPerformed(ActionEvent arg0) {
					try {
						GamePanel.this.pokerClient.sit(GamePanel.this.gameId, index);
						userPanel = getSeatPanel(index);
					} catch (RequestFailedException e) {
						log(e);
					}
				}
			});
			i = i + 1;
		}

		try {
			pokerClient.joinTable(gameId);
		} catch (RequestFailedException e) {
			log(e);
		}
	}

	public SeatPanel getSeatPanel(int index) {
		return seatPanelList.get(index);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		splitPane = new javax.swing.JSplitPane();
		logContainer = new javax.swing.JScrollPane();
		logTextArea = new javax.swing.JTextArea();
		gameContainer = new javax.swing.JPanel();
		tableContainer = new javax.swing.JPanel();
		seatPanel0 = new com.pokware.pokertester.SeatPanel();
		seatPanel1 = new com.pokware.pokertester.SeatPanel();
		seatPanel2 = new com.pokware.pokertester.SeatPanel();
		seatPanel3 = new com.pokware.pokertester.SeatPanel();
		potPanel1 = new PotPanel();
		seatPanel4 = new com.pokware.pokertester.SeatPanel();
		seatPanel5 = new com.pokware.pokertester.SeatPanel();
		seatPanel6 = new com.pokware.pokertester.SeatPanel();
		seatPanel7 = new com.pokware.pokertester.SeatPanel();
		jPanel2 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();

		setName("Form"); // NOI18N

		splitPane.setDividerLocation(550);
		splitPane.setResizeWeight(0.5);
		splitPane.setName("splitPane"); // NOI18N

		logContainer.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
		logContainer.setName("logContainer"); // NOI18N

		logTextArea.setColumns(20);
		logTextArea.setRows(5);
		logTextArea.setName("logTextArea"); // NOI18N
		logContainer.setViewportView(logTextArea);

		splitPane.setRightComponent(logContainer);

		gameContainer.setName("gameContainer"); // NOI18N

		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application
				.getInstance(com.pokware.pokertester.PokerTesterApplication.class).getContext().getResourceMap(GamePanel.class);
		tableContainer.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("tableContainer.border.title"))); // NOI18N
		tableContainer.setName("tableContainer"); // NOI18N
		tableContainer.setLayout(new java.awt.GridLayout(3, 3));
		seatPanelList = new java.util.ArrayList<SeatPanel>();
		seatPanelList.add(seatPanel0);
		seatPanelList.add(seatPanel1);
		seatPanelList.add(seatPanel2);
		seatPanelList.add(seatPanel3);
		seatPanelList.add(seatPanel4);
		seatPanelList.add(seatPanel5);
		seatPanelList.add(seatPanel6);
		seatPanelList.add(seatPanel7);

		seatPanel0.setName("seatPanel0"); // NOI18N
		tableContainer.add(seatPanel0);

		seatPanel1.setName("seatPanel1"); // NOI18N
		tableContainer.add(seatPanel1);

		seatPanel2.setName("seatPanel2"); // NOI18N
		tableContainer.add(seatPanel2);

		seatPanel3.setName("seatPanel3"); // NOI18N
		tableContainer.add(seatPanel3);

		potPanel1.setName("potPanel1"); // NOI18N
		tableContainer.add(potPanel1);

		seatPanel4.setName("seatPanel4"); // NOI18N
		tableContainer.add(seatPanel4);

		seatPanel5.setName("seatPanel5"); // NOI18N
		tableContainer.add(seatPanel5);

		seatPanel6.setName("seatPanel6"); // NOI18N
		tableContainer.add(seatPanel6);

		seatPanel7.setName("seatPanel7"); // NOI18N
		tableContainer.add(seatPanel7);

		jPanel2.setName("jPanel2"); // NOI18N
		jPanel2.setLayout(new java.awt.GridLayout(1, 4));

		jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
		jButton1.setName("jButton1"); // NOI18N
		jPanel2.add(jButton1);

		jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
		jButton3.setName("jButton3"); // NOI18N
		jPanel2.add(jButton3);

		jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
		jButton2.setName("jButton2"); // NOI18N
		jPanel2.add(jButton2);

		jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
		jButton4.setName("jButton4"); // NOI18N
		jPanel2.add(jButton4);

		javax.swing.GroupLayout gameContainerLayout = new javax.swing.GroupLayout(gameContainer);
		gameContainer.setLayout(gameContainerLayout);
		gameContainerLayout.setHorizontalGroup(gameContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				gameContainerLayout
						.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								gameContainerLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 526,
												Short.MAX_VALUE)
										.addComponent(tableContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 526,
												Short.MAX_VALUE)).addContainerGap()));
		gameContainerLayout.setVerticalGroup(gameContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				gameContainerLayout
						.createSequentialGroup()
						.addContainerGap()
						.addComponent(tableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(204, Short.MAX_VALUE)));

		splitPane.setLeftComponent(gameContainer);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(splitPane,
				javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(splitPane,
				javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE));
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel gameContainer;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane logContainer;
	private javax.swing.JTextArea logTextArea;
	private javax.swing.JPanel potPanel1;
	private com.pokware.pokertester.SeatPanel seatPanel0;
	private com.pokware.pokertester.SeatPanel seatPanel1;
	private com.pokware.pokertester.SeatPanel seatPanel2;
	private com.pokware.pokertester.SeatPanel seatPanel3;
	private com.pokware.pokertester.SeatPanel seatPanel4;
	private com.pokware.pokertester.SeatPanel seatPanel5;
	private com.pokware.pokertester.SeatPanel seatPanel6;
	private com.pokware.pokertester.SeatPanel seatPanel7;
	private javax.swing.JSplitPane splitPane;
	private javax.swing.JPanel tableContainer;
	private java.util.ArrayList<SeatPanel> seatPanelList;

	// End of variables declaration//GEN-END:variables

	private void log(RequestFailedException e) {
		logTextArea.append(e.getMessage());
	}

	private void log(Message event) {
		logTextArea.append(ProtobufTools.convertToString(event) + "\n");
	}

	@Override
	public void onBetEvent(BetEvent event) {
		log(event);
	}

	@Override
	public void onDealCardEvent(DealCardsEvent event) {
		log(event);
	}

	@Override
	public void onFlopEvent(FlopEvent event) {
		log(event);
	}

	@Override
	public void onHandStartEvent(HandStartEvent event) {
		log(event);
		int hole1 = event.getHole1();
		int hole2 = event.getHole2();
		userPanel.displayCards(hole1, hole2);
	}

	@Override
	public void onTableStatusEvent(TableStatusEvent event) {
		log(event);
	}

	@Override
	public void onSeatStatusEvent(SeatStatusEvent event) {
		log(event);
	}

	@Override
	public void onTimeOutEvent(TimeOutEvent event) {
		log(event);
	}

	@Override
	public void onWinEvent(WinEvent event) {
		log(event);
	}

	@Override
	public void onTurnEvent(TurnEvent event) {
		log(event);
	}
}
